CREATE TABLE IF NOT EXISTS profils (
  discord_id VARCHAR(64) PRIMARY KEY,
  pseudo VARCHAR(100) NOT NULL,
  avatar TEXT NULL,
  email VARCHAR(255) NULL,
  argent INT NOT NULL DEFAULT 0,
  xp INT NOT NULL DEFAULT 0,
  niveau INT NOT NULL DEFAULT 1,
  caisses_ouvertes INT NOT NULL DEFAULT 0,
  items_json JSON NULL,
  cree_le TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifie_le TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
